backend/modules/worker/models/StudentMark.php
<?php

namespace app\modules\worker\models;

use Yii;

/**
 * This is the model class for table "student_mark".
 *
 * @property integer $id
 * @property integer $subject_id
 * @property integer $student_id
 * @property string $mark_date
 * @property string $mark
 *
 * @property Subject $subject
 * @property SchoolStudent $student
 */
class StudentMark extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'student_mark';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['subject_id', 'student_id', 'mark_date', 'mark'], 'required'],
            [['subject_id', 'student_id'], 'integer'],
            [['mark_date'], 'safe'],
            [['mark'], 'string', 'max' => 10]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'subject_id' => 'Subject ID',
            'student_id' => 'Student ID',
            'mark_date' => 'Mark Date',
            'mark' => 'Mark',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubject()
    {
        return $this->hasOne(Subject::className(), ['id' => 'subject_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudent()
    {
        return $this->hasOne(SchoolStudent::className(), ['id' => 'student_id']);
    }
}

backend/modules/worker/controllers/StudentMarkController.php
<?php

namespace app\modules\worker\controllers;

use Yii;
use app\modules\administrator\models\StudentMark;
use app\modules\administrator\models\SchoolYear;
use app\modules\administrator\models\SchoolStudent;
use app\modules\administrator\models\StudentMarkSearch;
use app\modules\administrator\models\StudentFilterForm;
use app\modules\administrator\models\School;
use app\modules\administrator\models\Subject;
use app\modules\administrator\models\SchoolClass;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\modules\worker\controllers\DefaultController;
use yii\data\ActiveDataProvider;
use yii\data\SqlDataProvider;


/**
 * StudentMarkController implements the CRUD actions for StudentMark model.
 */
class StudentMarkController extends DefaultController
{

   /* public function actionIndex()
    {
        $studentFilterForm = new StudentFilterForm();
        $studentFilterForm->school_years = SchoolYear::find()->all();
        $studentFilterForm->subjectAll = Subject::find()->all();
        $studentFilterForm->subject=$_POST[StudentFilterForm][subject];
        if($studentFilterForm->load(\Yii::$app->request->post())) {
            $studentFilterForm->getStudentsOfClass();
            return $this->render('index', [
                'studentFilterForm' => $studentFilterForm,
            ]);
        }else {
            return $this->render('index', [
                'studentFilterForm' => $studentFilterForm,
            ]);
        }
    }*/

    public function actionIndex($school_year_id=null,$school_id=null,$school_class_id=null)
    {
        $studentFilterForm = new StudentFilterForm();

        if(($_POST[StudentFilterForm][school_year_id]!=null)&&
                ($_POST[StudentFilterForm][school_id]!=null)&&
                ($_POST[StudentFilterForm][school_class_id]!=null)) 
            {
                $studentFilterForm->school_years = SchoolYear::find()->all();
                if($studentFilterForm->load(\Yii::$app->request->post())) {
                    $studentFilterForm->getStudentsOfClass();
                    return $this->render('index', [
                    'studentFilterForm' => $studentFilterForm,
                    ]);
                }else{
                    return $this->render('index', [
                        'studentFilterForm' => $studentFilterForm,
                    ]);
                }
            }elseif(($school_year_id!=null)&&($school_id!=null)&&($school_class_id!=null)){
                $studentFilterForm->school_year_id=$school_year_id;
                $studentFilterForm->school_id=$school_id;
                $studentFilterForm->school_class_id=$school_class_id;
                $studentFilterForm->school_years = SchoolYear::find()->all();
                $studentFilterForm->getStudentsOfClass();
                return $this->render('index', [
                        'studentFilterForm' => $studentFilterForm,
                    ]);
            }else{
                $studentFilterForm->school_years = SchoolYear::find()->all();
                if($studentFilterForm->load(\Yii::$app->request->post())) {
                    $studentFilterForm->getStudentsOfClass();
                    return $this->render('index', [
                        'studentFilterForm' => $studentFilterForm,
                    ]);
                 }else{
                     return $this->render('index', [
                        'studentFilterForm' => $studentFilterForm,
                    ]);
                }
            }
    }   



    /**
     * Displays a single StudentMark model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id,$subject_id=null)
    {
        if(isset($_GET[Subject][id])){
            $id_of_subject=$_GET[Subject][id];
        }else{
            $id_of_subject=$subject_id;
        }

        $subject = new Subject();
        if($id_of_subject==null){
            return $this->render('view', [
                'subject'=> $subject,
                'student' => $this->findStudentById($id),
            ]);
        }else{
           // $dataProvider = $this->getStudentMarks($id, $_POST[Subject][id]);
            $dataProvider = new ActiveDataProvider([
                'query' => StudentMark::find()->where(['student_id'=> $id,'subject_id'=>$id_of_subject]),
                'pagination' => [
                   'pageSize' => 20,
                    ],
                ]);

            $model=$dataProvider->getModels();

            return $this->render('view', [
                'dataProvider' => $dataProvider,
                'subject'=> $subject,
                'student' => $this->findStudentById($id),
                'model' => $model,
            ]);
        }
    }

    /*protected function getStudentMarks($student_id, $subject_id)
    {
       $dataProvider = new ActiveDataProvider([
                'query' => StudentMark::find()
                        ->where(['student_id'=> $student_id,'subject_id'=>$subject_id])
                    ]);    
        return  $dataProvider;
    }*/

    /**
     * Creates a new StudentMark model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($student_id, $subject_id)
    {
        $model = new StudentMark();
        $model->student_id=$student_id;
        $model->subject_id=$subject_id;

        if ($model->load(Yii::$app->request->post())) {
            $studentMark = StudentMark::getMarkByStudentSubjectDate($model->student_id, $model->subject_id, $model->mark_date);
            if ($studentMark) {
                $studentMark->mark = $model->mark;
                $studentMark->save();
            } else {
                $model->save();
            }
            return $this->redirect(['view','id'=>$student_id, 'subject_id'=>$model->subject_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    } 

    /**
     * Updates an existing StudentMark model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $studentMark = StudentMark::getMarkByStudentSubjectDate($model->student_id, $model->subject_id, $model->mark_date);
            if ($studentMark) {
                $studentMark->mark = $model->mark;
                $studentMark->save();
            } else {
                $model->save();
            }
            return $this->redirect(['view','id'=> $model->student_id, 'subject_id'=>$model->subject_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    } 

    /**
     * Deletes an existing StudentMark model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model=$this->findModel($id);
        $student_id=$model->student_id;
        $subject_id=$model->subject_id;
        $model->delete();

        return $this->redirect(['view','id'=> $student_id, 'subject_id'=>$subject_id]);
    }

    /**
     * Finds the StudentMark model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return StudentMark the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = StudentMark::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionGetClasses() {
        $params = json_decode(file_get_contents('php://input'));
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        if ($params->data->schoolYearId && $params->data->schoolId) {
            $schoolClasses = SchoolClass::find()
                ->join('JOIN', 'school_history', 'school_class.school_id = school_history.id')
                ->join('JOIN', 'school_year', 'school_year.id = school_history.school_year_id')
                ->where('school_history.school_id = :school_id AND school_year.id = :school_year_id', [':school_id' => $params->data->schoolId, 'school_year_id' => $params->data->schoolYearId])
                ->all();
            return $schoolClasses;
        } else {
            return null;
        }
    }

    public function actionGetSchools() {
        $params = json_decode(file_get_contents('php://input'));
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        if ($params->data->schoolYearId) {
            $schools = School::find()
                ->join('JOIN', 'school_history', 'school.id = school_history.school_id')
                ->join('JOIN', 'school_year', 'school_year.id = school_history.school_year_id')
                ->where('school_year.id = :school_year_id', ['school_year_id' => $params->data->schoolYearId])
                ->all();
            return $schools;
        } else {
            return null;
        }
    }

    protected function findStudentById($id)
    {
        $student = SchoolStudent::find()->where(['id'=>$id])->one();
            return $student;
    }    

}

backend/modules/worker/views/student-mark/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\modules\administrator\models\Subject;
use app\modules\administrator\models\SchoolStudent;
use dosamigos\datepicker\DatePicker;

/* @var $this yii\web\View */
/* @var $model backend\modules\administrator\models\StudentMark */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="student-mark-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'mark_date')->widget(DatePicker::className(),[
		'language' => 'ru',
		'clientOptions'=>[
			'format'=>'yyyy-mm-dd']
		]) ?>
	
    <?= $form->field($model, 'mark')->textInput(['maxlength' => true]) ?>
	
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Добавить' : 'Обновить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/worker/views/student-mark/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\modules\administrator\models\StudentMarkSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="student-mark-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'subject_id') ?>

    <?= $form->field($model, 'student_id') ?>

    <?= $form->field($model, 'mark_date') ?>

    <?= $form->field($model, 'mark') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/worker/views/student-mark/_student_filter_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use backend\assets\StudentFilterAsset;
use yii\grid\GridView;
use yii\helpers\Url;
use app\modules\administrator\models\SchoolStudent;
use app\modules\administrator\models\Student;


StudentFilterAsset::register($this);
/* @var $this yii\web\View */
/* @var $model common\models\ParentProfile */
/* @var $form yii\widgets\ActiveForm */
?>

<div ng-app="studentFilterApp" class="administrator-default-index">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <div class="row">
                <div class="col-md-3">
                    <h2 style="margin-top: 0">Фильтр учащихся</h2>
                </div>
                <div class="col-md-3">
                    <span class="spinner" style="display:none"></span>
                </div>
            </div>
        </div>
        <div class="panel-body">

            <?php $form = ActiveForm::begin(); ?>

                <div ng-controller="FilterForm" class="row">
                    <div class="col-md-4">
                    
                        <?= $form->field($studentFilterForm, 'school_year_id')->dropdownList(ArrayHelper::map($studentFilterForm->school_years, 'id',
                                    function($model, $defaultValue) {
                                        return $model->start_year.' - '.$model->end_year;
                                    }), ['prompt' => '---Учебный год---','ng-model' => 'schoolYearId']) ?>

                    </div>
                    <div class="col-md-4">
                    
                        <?= $form->field($studentFilterForm, 'school_id')->dropdownList(['prompt' => '---Школа---'], ['ng-model' => 'selectedSchool.id', 'ng-options' => 'school.id as school.name for school in schools track by school.id', ]) ?>

                    </div>
                    <div class="col-md-4">
                    
                        <?= $form->field($studentFilterForm, 'school_class_id')->dropdownList(['prompt' => '---Класс---'], ['ng-model' => 'selectedClass.id', 'ng-options' => 'class.id as class.name for class in schoolClasses track by class.id', ]) ?>

                    </div>
                </div>

                <div class="row text-right">
                    <div class="col-md-12">

                        <?= Html::submitButton('Найти', ['class' => 'btn btn-success' ]) ?>
                    
                    </div>
                </div>

            <?php ActiveForm::end(); ?>
            
        </div>
    </div>

    <?php
   // print_r("<pre>");print_r($studentFilterForm->filteredStudentsOfClassDataProvider);print_r("</pre>");
        if ($studentFilterForm->filteredStudentsOfClassDataProvider)  { ?>

            
            <?= Html::tag('span', $studentFilterForm->currentSchoolYear->start_year.' - '.$studentFilterForm->currentSchoolYear->end_year, ['class'=>'label label-primary']) ?>
            <?= Html::tag('span', $studentFilterForm->currentSchool->name, ['class'=>'label label-primary']) ?>
            <?= Html::tag('span', $studentFilterForm->currentClass->name, ['class'=>'label label-primary']) ?>


            <?=  GridView::widget([
                'dataProvider' => $studentFilterForm->filteredStudentsOfClassDataProvider,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],
                    [
                    //'attribute'=>'student_id',
                    'label'=>'Учащиеся',
                    'value'=> function($model){
                        return $model->personalNumber->surname." "
                            .$model->personalNumber->name." "
                            .$model->personalNumber->lastname;
                    }
                    ],
                    [ 
                    'class' => 'yii\grid\ActionColumn',
                    'controller' => 'student-mark',
                    'template' => '{view}',
                    /*'buttons' => [
                    'view' => function ($model) {
                        return Html::a('<span class="glyphicon glyphicon-user"></span>', 
                            ['view','student_id'=>$model->id], 
                            ['title' => "Оценки учащегося"]);
                        },
                    ],*/
                    ],
                ],
            ]); ?>

    <?php } ?>

</div>

backend/modules/worker/views/student-mark/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\modules\administrator\models\StudentMark */
$fio=$model->student->personalNumber->surname." "
.$model->student->personalNumber->name." ".$model->student->personalNumber->lastname;
$this->title = 'Добавить оценку';
$this->params['breadcrumbs'][] = ['label' => 'Оценки учащихся', 
    'url' => ['student-mark/index','school_year_id'=>$model->student->schoolClass->school->school_year_id,
                'school_id'=>$model->student->schoolClass->school->school_id,
                'school_class_id'=>$model->student->school_class_id]];
$this->params['breadcrumbs'][] = ['label' => $fio, 'url' => ['student-mark/view', 'id'=>$model->student_id]];
$this->params['breadcrumbs'][] = ['label'=>$model->subject->name, 'url'=>['student-mark/view','id'=>$model->student_id,
																				'subject_id'=>$model->subject->id ]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="student-mark-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/modules/worker/views/student-mark/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use app\modules\administrator\models\SchoolStudent;
use app\modules\administrator\models\Subject;


/* @var $this yii\web\View */
/* @var $searchModel backend\modules\administrator\models\StudentMarkSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Оценки учащихся';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="student-mark-index">

    <?= $this->render('_student_filter_form', [
        'studentFilterForm' => $studentFilterForm,
    ]) ?>

</div>

backend/modules/worker/views/student-mark/student_marks.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\modules\administrator\models\ParentProfileSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Оценки учащегося по предмету';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="student-marks">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $studentFilterForm->filteredStudentsMarksDataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
          
            'mark',
            'mark_date',
            
            [
            'class' => 'yii\grid\ActionColumn',
			],

			],
    ]); ?>

</div>

backend/modules/worker/views/student-mark/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\modules\administrator\models\StudentMark */
$fio=$model->student->personalNumber->surname." "
.$model->student->personalNumber->name." ".$model->student->personalNumber->lastname;
$this->title = 'Обновить оценку учащемуся: '.$fio.''; 
$this->params['breadcrumbs'][] = ['label' => 'Оценки учащихся', 
    'url' => ['student-mark/index','school_year_id'=>$model->student->schoolClass->school->school_year_id,
                'school_id'=>$model->student->schoolClass->school->school_id,
                'school_class_id'=>$model->student->school_class_id]];
$this->params['breadcrumbs'][] = ['label' => $fio, 'url' => ['student-mark/view', 'id'=>$model->student_id]];
$this->params['breadcrumbs'][] = ['label' => $model->subject->name, 'url' => ['student-mark/view', 'id'=>$model->student_id,
														'subject_id'=> $model->subject_id]];
$this->params['breadcrumbs'][] = 'Обновить';
?>
<div class="student-mark-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/modules/worker/views/student-mark/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use app\modules\administrator\models\Subject;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $model backend\modules\administrator\models\StudentMark */

$this->title = $student->personalNumber->surname." ".$student->personalNumber->name." ".$student->personalNumber->lastname;
$this->params['breadcrumbs'][] = ['label' => 'Оценки учащихся', 
    'url' => ['student-mark/index','school_year_id'=>$student->schoolClass->school->school_year_id,
                'school_id'=>$student->schoolClass->school->school_id,
                'school_class_id'=>$student->school_class_id]];
$this->params['breadcrumbs'][] = $this->title;
$this->params['breadcrumbs'][] = $model[0]->subject->name;
?>
<div class="student-mark-view">

    <h2><?= Html::encode($this->title) ?></h2>

    <?php $form = ActiveForm::begin([
        'method' => 'GET',
        'action' => ['student-mark/view','id'=>$student->id]
        ]); ?>
     
        <div class="col-md-3">
            
            <?= $form->field($subject, 'id')->dropDownList(ArrayHelper::map(Subject::find()->all(), 'id', 'name'), 
                                                            array('prompt'=>'---Предмет---')) ?>

        </div>

    
        <div class="col-md-12">

            <p>
                <?= Html::submitButton('Найти', ['class' => 'btn btn-success']) ?>
            </p>
         
        </div>

    <?php ActiveForm::end(); ?>
  
</div>

<div class="row">
    <div class="col-md-12">    
    <?php
/*    print_r("<pre>"); 
    print_r($model); 
    print_r("</pre>"); */
   if($dataProvider){ ?>
        
          <?php if(isset($_GET[Subject][id])){
            $id_of_subject=$_GET[Subject][id];
        }else{
            $id_of_subject=\Yii::$app->getRequest()->getQueryParam('subject_id');
        } ?>



        <p>
        <?= Html::a('Добавить оценку', ['create', 'student_id'=> \Yii::$app->getRequest()->getQueryParam('id'), 
            'subject_id'=> $id_of_subject], 
                ['class' => 'btn btn-success']) ?>
        </p>

         <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                
                'mark',
                'mark_date',
            
                ['class' => 'yii\grid\ActionColumn',
                'template' => '{update} {delete}',
                ],
            ],

        ]); ?>
   <?php }
    ?>
</div>
</div>