backend/modules/administrator/models/Video.php
<?php

namespace app\modules\administrator\models;

use yii\base\Model;
use Yii;
use Yii\web\UploadedFile;
use app\modules\administrator\models\UploadForm;


/**
 * This is the model class for table "video".
 *
 * @property integer $id
 * @property string $name
 */
class Video extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'video';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 255],
			[['description'], 'safe'],
			[['publish'], 'boolean'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
			'description' => 'Описание',
			'publish' => 'Опубликовано',
        ];
    }
}

backend/modules/administrator/controllers/VideoController.php
<?php

namespace app\modules\administrator\controllers;

use Yii;
use app\modules\administrator\models\Video;
use app\modules\administrator\models\UploadForm;
use app\modules\administrator\models\VideoSearch;
use app\modules\administrator\models\PartnerSearch;
use app\modules\administrator\models\SchoolPartnerSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use common\helpers\Translit;
use app\modules\administrator\controllers\DefaultController;

/**
 * VideoController implements the CRUD actions for Video model.
 */
class VideoController extends DefaultController
{
    /**
     * Lists all Video models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new VideoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination->pageSize=10;

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);

    }

    /**
     * Displays a single Video model.
     * @param integer $id
     * @return mixed
     */
    /*public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }*/

    /**
     * Creates a new Video model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
	public function actionUpload()
    {
        $model = new UploadForm();
		//added
		$model_1 = new Video();
		
        if (Yii::$app->request->isPost) {
            $model->myFile = UploadedFile::getInstance($model, 'myFile');
			
            if($model->myFile==null){
                Yii::$app->getSession()->setFlash('error', 'Выберите файл');
                return $this->redirect(['upload']);
            } 
               
			//added transliteration
			$translit_name=Translit::transliteration($model->myFile->baseName);
			
				if ($model->upload($translit_name)) {
					//added translit_name saving with extension
					$model_1->load(Yii::$app->request->post());
					$model_1->name=$model->translit_name. '.' . $model->myFile->extension;
					$model_1->save();
					return $this->redirect(['index']);
				}
			} 
		return $this->render('upload', ['model' => $model, 'model_1' => $model_1]);
	}
    

    /**
     * Updates an existing Video model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
		
		$file_name = $model->name;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
			//added
				rename('../frontend/uploads/' . $file_name, '../frontend/uploads/' . $model->name);
		   return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Video model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */

	//added {file deleting}

    public function actionDelete($id)
    {
		//added file deleting
		unlink('../frontend/uploads/' . $this->findModel($id)->name);
			
        $this->findModel($id)->delete();
		return $this->redirect(['index']);
    }

    /**
     * Finds the Video model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Video the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Video::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/modules/administrator/views/video/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\Partner */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="partner-form">

    <?php $form = ActiveForm::begin((['options' => ['enctype' => 'multipart/form-data']]) ); ?>

    <?= $form->field($model, 'name')->textInput() ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>
	
	<?= $form->field($model, 'publish')->checkbox(['checked' => true]) ?>


    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Загрузить' : 'Обновить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/administrator/views/video/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\VideoSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="video-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/administrator/views/video/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\Video */

$this->title = 'Create Video';
$this->params['breadcrumbs'][] = ['label' => 'Videos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="video-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/modules/administrator/views/video/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
//use backend\controllers\PartnerController;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\VideoSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Видео';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="video-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Загрузить видео', ['video/upload'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'name',
			'description',
			'publish:boolean',

            ['class' => 'yii\grid\ActionColumn',
			  'controller' => 'video',
			  'template' => '{update} {delete}',
			],		
        ],
    ]); 
	?>
</div>	

backend/modules/administrator/views/video/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Video */

$this->title = 'Обновить видео: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Видео', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Обновить';
?>
<div class="video-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/modules/administrator/views/video/upload.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\Video */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="video-form">

    <?php $form = ActiveForm::begin((['options' => ['enctype' => 'multipart/form-data']]) ); ?>
	
    <?= $form->field($model_1, 'description')->textarea(['rows' => 6]) ?>
	
	<?= $form->field($model, 'myFile')->fileInput() ?>
	
	<?= $form->field($model_1, 'publish')->checkbox(['checked' => true]) ?>
		
	<div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Загрузить' : 'Обновить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>
	
    <?php ActiveForm::end(); ?>

</div>

backend/modules/administrator/views/video/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Video */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Videos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="video-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
			'description'
        ],
    ]) ?>

</div>